version: 2.1

jobs:
  test-ruby2-4:
    docker:
      - image: circleci/ruby:2.4.5
    working_directory: ~/bulk
    steps:
      - checkout
      - run:
          command: bundle config rubygems.pkg.github.com __GEM_USERNAME__:__GEM_PASSWORD__
      - run:
          command: bundle install
      - run:
          command: bundle exec rake

  test-ruby2-5:
    docker:
      - image: circleci/ruby:2.5.5
    working_directory: ~/bulk
    steps:
      - checkout
      - run:
          command: bundle config rubygems.pkg.github.com __GEM_USERNAME__:__GEM_PASSWORD__
      - run:
          command: bundle install
      - run:
          command: bundle exec rake


workflows:
  version: 2.1
  build-deploy:
    jobs:
      - test-ruby2-4
      - test-ruby2-5
